apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pikz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-pikz@sha256:991fda83701dd0c0bd53cd9f3f2df896e6588f659c4c355b8aa7c8dae120b4cc
        name: my-nodejs
        resources: {}
status: {}
